import { esc, isSafeHref } from './security.mjs';

const STATUS_ICON = { pass: '✅', fail: '❌', skip: '⏭️', error: '⚠️' };
const STATUS_CLASS = { pass: 'pass', fail: 'fail', skip: 'skip', error: 'error' };
const SEV_CLASS = { critical: 'sev-critical', serious: 'sev-serious', moderate: 'sev-moderate', info: 'sev-info' };

function css() {
  return `
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f5f6fa;color:#1a1a2e;line-height:1.5;padding:2rem}
.container{max-width:1100px;margin:0 auto}
h1{font-size:1.75rem;margin-bottom:.25rem}
.subtitle{color:#666;margin-bottom:1.5rem;font-size:.9rem}
.score-cards{display:flex;gap:1rem;flex-wrap:wrap;margin-bottom:2rem}
.score-card{background:#fff;border-radius:12px;padding:1.25rem;flex:1;min-width:140px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.06)}
.score-card .score{font-size:2.5rem;font-weight:700;line-height:1}
.score-card .label{font-size:.75rem;color:#888;margin-top:.25rem;text-transform:uppercase;letter-spacing:.05em}
.score-pass .score{color:#0a7}
.score-fail .score{color:#e44}
.score-skip .score{color:#aaa}
.score-error .score{color:#f80}
.check{background:#fff;border-radius:10px;margin-bottom:1rem;box-shadow:0 1px 4px rgba(0,0,0,.05);overflow:hidden}
.check-header{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.25rem;cursor:pointer;user-select:none}
.check-header:hover{background:#fafbfd}
.check-title{font-weight:600;font-size:1rem}
.check-meta{display:flex;gap:1rem;align-items:center;font-size:.85rem;color:#666}
.check-badge{display:inline-block;padding:.15rem .6rem;border-radius:20px;font-size:.75rem;font-weight:600;color:#fff}
.badge-pass{background:#0a7}
.badge-fail{background:#e44}
.badge-skip{background:#bbb}
.badge-error{background:#f80}
.check-body{padding:0 1.25rem 1.25rem;display:none}
.check.open .check-body{display:block}
.finding{padding:.5rem 0;border-bottom:1px solid #f0f0f0;font-size:.9rem}
.finding:last-child{border-bottom:none}
.sev-critical{color:#c00;font-weight:600}
.sev-serious{color:#e44}
.sev-moderate{color:#f80}
.sev-info{color:#888}
.finding-url{font-size:.8rem;color:#06c;word-break:break-all}
.compare-row{display:grid;grid-template-columns:1fr 100px 100px 80px;gap:.5rem;align-items:center;padding:.75rem 1.25rem;border-bottom:1px solid #f0f0f0}
.compare-row:first-child{font-weight:700;background:#f8f9fc}
.delta-pos{color:#0a7;font-weight:600}
.delta-neg{color:#e44;font-weight:600}
.delta-na{color:#aaa}
.asymmetric-warning{background:#fff7e6;border:1px solid #ffd666;border-radius:8px;padding:1rem;margin-bottom:1.5rem;font-size:.9rem}
footer{margin-top:2rem;padding-top:1rem;border-top:1px solid #e0e0e0;font-size:.8rem;color:#999;text-align:center}
`;
}

function js() {
  return `document.querySelectorAll('.check-header').forEach(h=>{h.onclick=()=>h.parentElement.classList.toggle('open')})`;
}

function head(title) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data: https:; script-src 'unsafe-inline'">
<title>${esc(title)}</title>
<style>${css()}</style>
</head>
<body>
<div class="container">`;
}

function foot(auditedAt) {
  return `</div>
<footer>Generated by cc-site-audit &middot; ${esc(auditedAt)}</footer>
<script>${js()}</script>
</body>
</html>`;
}

function scoreCard(label, score, status) {
  const display = score !== null ? String(score) : (status === 'skip' ? '—' : '?');
  return `<div class="score-card score-${STATUS_CLASS[status] || 'skip'}">
  <div class="score">${esc(display)}</div>
  <div class="label">${esc(label)}</div>
</div>`;
}

function renderFindings(findings) {
  if (!findings.length) return '<p style="color:#888;font-size:.9rem">No findings.</p>';
  let html = '';
  for (const f of findings) {
    const urlPart = f.url
      ? (isSafeHref(f.url) ? `<div class="finding-url"><a href="${esc(f.url)}">${esc(f.url)}</a></div>` : `<div class="finding-url">${esc(f.url)}</div>`)
      : '';
    html += `<div class="finding ${SEV_CLASS[f.severity] || ''}">
  <span>${esc(f.severity)}</span>: ${esc(f.message)}
  ${f.context ? `<div style="font-size:.8rem;color:#888;margin-top:.2rem">${esc(f.context)}</div>` : ''}
  ${urlPart}
</div>`;
  }
  return html;
}

function checkSection(result) {
  const badge = `<span class="check-badge badge-${STATUS_CLASS[result.status]}">${esc(result.status)}${result.grade ? ' ' + esc(result.grade) : ''}${result.score !== null ? ' ' + result.score + '/100' : ''}</span>`;
  const findingsCount = result.findings.length ? `${result.findings.length} finding${result.findings.length > 1 ? 's' : ''}` : '';
  const reason = result.reason ? `<span style="color:#888"> — ${esc(result.reason)}</span>` : '';

  return `<div class="check" data-check-id="${esc(result.checkId)}">
  <div class="check-header">
    <span class="check-title">${STATUS_ICON[result.status] || ''} ${esc(result.tool)}</span>
    <div class="check-meta">
      <span>${findingsCount}</span>
      ${badge}${reason}
    </div>
  </div>
  <div class="check-body">
    ${renderFindings(result.findings)}
  </div>
</div>`;
}

/**
 * Render a single-site audit report as a standalone HTML string.
 * @param {import('./orchestrator.mjs').SiteReport} report
 * @returns {string}
 */
export function renderSingle(report) {
  const title = `Site Audit — ${report.url}`;
  const passed = report.results.filter(r => r.status === 'pass').length;
  const total = report.results.filter(r => r.status !== 'skip').length;

  const topScores = report.results
    .filter(r => r.score !== null && r.status !== 'skip')
    .slice(0, 5);

  let html = head(title);
  html += `<h1>${esc(title)}</h1>`;
  html += `<div class="subtitle">${esc(report.auditedAt)} &middot; ${passed}/${total} checks passed &middot; ${(report.totalDurationMs / 1000).toFixed(1)}s</div>`;

  if (topScores.length) {
    html += '<div class="score-cards">';
    for (const r of topScores) {
      html += scoreCard(r.tool, r.score, r.status);
    }
    html += '</div>';
  }

  for (const result of report.results) {
    html += checkSection(result);
  }

  html += foot(report.auditedAt);
  return html;
}

/**
 * Render a comparison report as a standalone HTML string.
 * @param {import('./diff.mjs').DeltaReport} delta
 * @returns {string}
 */
export function renderComparison(delta) {
  const title = `Site Comparison — ${delta.urlA} vs ${delta.urlB}`;

  let html = head(title);
  html += `<h1>${esc(title)}</h1>`;
  html += `<div class="subtitle">${esc(delta.auditedAt)}</div>`;

  const { aOnly, bOnly } = delta.summary;
  if (aOnly > 0 || bOnly > 0) {
    html += `<div class="asymmetric-warning">Asymmetric availability: `;
    if (aOnly > 0) html += `${aOnly} check${aOnly > 1 ? 's' : ''} ran only for site A. `;
    if (bOnly > 0) html += `${bOnly} check${bOnly > 1 ? 's' : ''} ran only for site B. `;
    html += `Deltas for one-sided checks show N/A.</div>`;
  }

  html += '<div style="background:#fff;border-radius:10px;box-shadow:0 1px 4px rgba(0,0,0,.05);overflow:hidden;margin-bottom:2rem">';
  html += `<div class="compare-row"><span>Check</span><span>Site A</span><span>Site B</span><span>Delta</span></div>`;

  for (const d of delta.deltas) {
    const aDisplay = d.a && d.a.status !== 'skip'
      ? (d.a.score !== null ? `${d.a.score}` : d.a.status)
      : '—';
    const bDisplay = d.b && d.b.status !== 'skip'
      ? (d.b.score !== null ? `${d.b.score}` : d.b.status)
      : '—';

    let deltaDisplay;
    if (d.deltaScore === null) {
      deltaDisplay = '<span class="delta-na">N/A</span>';
    } else if (d.deltaScore > 0) {
      deltaDisplay = `<span class="delta-pos">+${d.deltaScore}</span>`;
    } else if (d.deltaScore < 0) {
      deltaDisplay = `<span class="delta-neg">${d.deltaScore}</span>`;
    } else {
      deltaDisplay = '<span>0</span>';
    }

    html += `<div class="compare-row">
  <span>${esc(d.tool)}</span>
  <span>${esc(aDisplay)}</span>
  <span>${esc(bDisplay)}</span>
  <span>${deltaDisplay}</span>
</div>`;
  }

  html += '</div>';

  for (const d of delta.deltas) {
    if (d.a) html += checkSection(d.a);
    if (d.b && d.availability === 'both') {
      html += checkSection({ ...d.b, tool: `${d.b.tool} (Site B)` });
    } else if (d.b && d.availability === 'site-b-only') {
      html += checkSection(d.b);
    }
  }

  html += foot(delta.auditedAt);
  return html;
}
